### ISSUE TITLE
Отправка сообщения на кириллице

### ISSUE THREAD

**Issue by dkodnik** [dkodnik/1cxmpp#1]
При отправке сообщения на русском, 1С вылетает по ошибке

**Comment by vitalyster** [comment]
> ТестЗапроса = ""<body content='text/xml; charset=utf-8' from='""+Объект.Пользователь

Очевидно, `Объект.Пользователь` (и все остальные строки) хранятся в 1С в UTF-16 и их нужно перекодировать в UTF-8 (как это делается в `HTTPЗапрос`, например)

**Comment by vitalyster** [comment]
> ТекстФайл.Записать(ФайлТелаЗапроса, КодировкаТекста.ANSI);
Собственно, вот тут и есть баг ;)
